# Generated by Django 2.0.7 on 2018-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_column='name', max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('policyno', models.IntegerField(max_length=10)),
                ('date', models.CharField(max_length=25)),
            ],
        ),
    ]
